backend_repo_url: "https://github.com/Chinenye-Consults/book-review-app.git"
backend_app_port: 3001
db_host: "bookreview-mysql.mysql.database.azure.com"
db_user: "mysqladmin"
db_password: "Churchhill@123"
db_name: "book_review_db"
jwt_secret: "92dced19f997374d785c3e90d0f951590e2e0c6f1d1db4a404a2263715459261"
allowed_origins: "http://51.144.77.241:3000"    #Frontend VM IP address
